name: integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install
      run: npm ci --include=dev

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
