name: update-bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly at 12 AM UTC on Sunday

jobs:
  updater:
    runs-on: ubuntu-24.04
    permissions: 
      contents: write # allow action to create branch
      pull-requests: write # allow this action to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
    
      - id: theirs
        name: Determine latest @mdi/js version
        run: |
          echo "version=$(npm show @mdi/js version)" >> "$GITHUB_OUTPUT"
      
      - name: Determine current @maxle5/mdi-vue version
        uses: rexdefuror/read-package-json@v1.0.5        

      - name: Bump package.json version
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}  
        uses: dmikey/package-json-version@v0.0.2
        with:
          # This will be the version you want to set in the package.json file
          version: ${{ steps.theirs.outputs.version }}
          git-tag-version: false

      - name: Update/Create vue components
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}        
        run: |
          npm install @mdi/js@latest -D
          npm install
          npm run generate

      - name: Create Pull Request
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}  
        uses: peter-evans/create-pull-request@v6
        with: 
          title: "task: updated @mdi/js to ${{ steps.theirs.outputs.version }}"
          body: "Updated to the latest version of [@mdi/js](https://github.com/Templarian/MaterialDesign-JS)"
          branch: update-mdi
          delete-branch: true
          commit-message: |
            updated @mdi/js to v${{ steps.theirs.outputs.version  }}
          
