name: updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 12 AM UTC every day

jobs:
  updater:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
    
      - id: theirs
        name: Determine latest @mdi/svg version
        run: |
          echo "version=$(npm show @mdi/svg version)" >> "$GITHUB_OUTPUT"
      
      - name: Determine current @maxle5/mdi-vue version
        uses: rexdefuror/read-package-json@v1.0.5        

      - name: Bump package.json version
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}  
        uses: dmikey/package-json-version@v0.0.2
        with:
          # This will be the version you want to set in the package.json file
          version: ${{ steps.theirs.outputs.version }}
          git-tag-version: false

      - name: Update/Create vue components
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}        
        run: |
          npm install @mdi/svg@latest -D
          npm install
          npm run generate

      - name: Create Pull Request
        if: ${{ env.PACKAGE_VERSION != steps.theirs.outputs.version }}  
        uses: peter-evans/create-pull-request@v6
        with: 
          branch: update-mdi
          delete-branch: true
          commit-message: |
            updated to latest mdi
